### ISSUE TITLE
[bug] crashes on ubuntu

### ISSUE THREAD

**Issue by dreais** [dreais/wFita#52]
**Describe the bug**
cannot run the binary after building it. it crashes before printing anything

**To Reproduce**
```bash
make
./wFita
```

**Expected behavior**
the map to be printed

**Suggested resolution**
valgrind is addressing the issue to print_room.c:166

**Desktop information**
Ubuntu 18.04, using i3, on urxvt

**Comment by arpit-saxena** [comment]
Doesn't work on Manjaro either (kinda expected as it doesn't work on Ubuntu). 
Manjaro 18.1.5, using i3, on termite.

PS: Is this project still being worked on?

**Comment by dreais** [comment]
hello! thanks for the feedback :) 
indeed, quite expected and i have frankly no idea at the time. i'd advise you to use a wide resolution terminal to ensure this is not an issue.

as for the P.S., yes, this project is still on-going! my job is taking my time (and life), but that apart i intend to continue it :)
(PPS: https://discord.gg/vFYXHq5 i hang out on discord more often, feel free to come and discuss there)
